services:
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./_docker_volumes/redis:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./_docker_volumes/postgres:/var/lib/postgresql/data

  # minio:
  #   image: minio/minio
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
  #     - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   command: minio server --console-address ":9001" /data
  #   volumes:
  #     - ./_docker_volumes/minio:/data

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - '8025:8025'
  #     - '1025:1025'
